version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: taffu@123
      MYSQL_DB: two=tier
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: taffu@123
      MYSQL_USER: devops
      MYSQL_PASSWORD: taffu
      MYSQL_DATABASE: two=tier
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:  
